In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from IPython.core.display import HTML
HTML("<style>.container { width:100% !important; }</style>")

In [3]:
from KuhnPoker import KuhnPokerModel, KuhnPokerInfoSet, ActionNode, PASS, ADD_CHIP, Card
from ISMCTS import Tree, Constants
from AlphaZero import NNModel, SelfPlayDataV, SelfPlayDataP

import numpy as np
import pickle
import pandas as pd
from tqdm import tqdm

import torch

In [4]:
with open('self_play_games/games.pkl', 'rb') as file:
    games = pickle.load(file)

In [5]:
games

[TurnSnapshot(info_set=[0], cards=KQ, action_dist={0: 1.0, 1: 0.0}, action=0, game_id=0, gen_id=0, outcome=-1.0),
 TurnSnapshot(info_set=[0], cards=JQ, action_dist={0: 1.0, 1: 0.0}, action=0, game_id=1, gen_id=0, outcome=1.0),
 TurnSnapshot(info_set=[0], cards=JQ, action_dist={0: 1.0, 1: 0.0}, action=0, game_id=2, gen_id=0, outcome=1.0),
 TurnSnapshot(info_set=[0], cards=QJ, action_dist={0: 0.67, 1: 0.33}, action=0, game_id=3, gen_id=0, outcome=-1.0),
 TurnSnapshot(info_set=[0], cards=KJ, action_dist={0: 0.67, 1: 0.33}, action=1, game_id=4, gen_id=0, outcome=-2.0),
 TurnSnapshot(info_set=[01], cards=KJ, action_dist={0: 0.0, 1: 1.0}, action=1, game_id=4, gen_id=0, outcome=2.0),
 TurnSnapshot(info_set=[0], cards=KQ, action_dist={0: 1.0, 1: 0.0}, action=0, game_id=0, gen_id=1, outcome=-1.0),
 TurnSnapshot(info_set=[0], cards=JK, action_dist={0: 0.0, 1: 1.0}, action=1, game_id=1, gen_id=1, outcome=1.0),
 TurnSnapshot(info_set=[01], cards=JK, action_dist={0: 1.0, 1: 0.0}, action=0, game_id=

In [6]:
vmodel = torch.load('model/vmodel.pt')

In [7]:
datasetV = SelfPlayDataV(games)

In [8]:
[vmodel(x).detach().numpy() for x, v in datasetV]

[array([[-2.6725233e-05],
        [-1.3999518e+00],
        [-9.9993420e-01]], dtype=float32),
 array([[-2.6725233e-05],
        [ 9.9995345e-01],
        [ 9.9997985e-01]], dtype=float32),
 array([[-2.6725233e-05],
        [ 9.9995345e-01],
        [ 9.9997985e-01]], dtype=float32),
 array([[-1.4999245e+00],
        [-1.4086813e-04],
        [-9.9986577e-01]], dtype=float32),
 array([[-1.4999245],
        [-1.3999518],
        [-1.6666752]], dtype=float32),
 array([[1.9996841],
        [1.9998766],
        [1.9999325]], dtype=float32),
 array([[-2.6725233e-05],
        [-1.3999518e+00],
        [-9.9993420e-01]], dtype=float32),
 array([[0.9999925 ],
        [0.99995345],
        [1.0000215 ]], dtype=float32),
 array([[-1.000065 ],
        [-0.9999453],
        [-1.0000079]], dtype=float32),
 array([[-1.4999245],
        [-1.3999518],
        [-1.6666752]], dtype=float32),
 array([[1.9996841],
        [1.9998766],
        [1.9999325]], dtype=float32),
 array([[ 9.9999249e-01],
       

In [10]:
pmodel = torch.load('model/pmodel.pt')

In [11]:
datasetP = SelfPlayDataP(games)

In [12]:
[pmodel(x).detach().numpy()[0] for x, p in datasetP]

[0.011273608,
 0.011273608,
 0.011273608,
 0.32974765,
 0.32974765,
 0.9957361,
 0.011273608,
 0.9888207,
 0.008277346,
 0.32974765,
 0.9957361,
 0.9888207,
 0.33009255,
 0.32974765]

In [13]:
list(datasetP)

[(tensor([ 0., -1., -1., -1.,  1.]), tensor([0.])),
 (tensor([ 0., -1., -1., -1.,  1.]), tensor([0.])),
 (tensor([ 0., -1., -1., -1.,  1.]), tensor([0.])),
 (tensor([ 0., -1., -1., -1.,  0.]), tensor([0.3300])),
 (tensor([ 0., -1., -1., -1.,  0.]), tensor([0.3300])),
 (tensor([ 0.,  1., -1.,  2., -1.]), tensor([1.])),
 (tensor([ 0., -1., -1., -1.,  1.]), tensor([0.])),
 (tensor([ 0., -1., -1., -1.,  2.]), tensor([1.])),
 (tensor([ 0.,  1., -1.,  0., -1.]), tensor([0.])),
 (tensor([ 0., -1., -1., -1.,  0.]), tensor([0.3300])),
 (tensor([ 0.,  1., -1.,  2., -1.]), tensor([1.])),
 (tensor([ 0., -1., -1., -1.,  2.]), tensor([1.])),
 (tensor([ 0.,  1., -1.,  1., -1.]), tensor([0.3300])),
 (tensor([ 0., -1., -1., -1.,  0.]), tensor([0.3300]))]